
stages:
  - install
  - build
before_script:
  - export PATH=$PATH:$HOME/.nvm/versions/node/v11.11.0/bin/

cache:
  paths:
    - node_modules/

InstallDependencies:
  stage: install
  script:
    - npm install

Build:
  stage: build
  cache:
    untracked: false
  script:
    - ls